# Generated by Django 4.1.4 on 2022-12-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lekarze', '0002_wizyta'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyta',
            name='lekarz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lekarze.lekarze'),
        ),
    ]
