# Generated by Django 4.1.4 on 2023-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lekarze', '0003_wizyta_lekarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_leku', models.DecimalField(decimal_places=0, max_digits=5)),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lek',
                'verbose_name_plural': 'Leki',
            },
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
            options={
                'verbose_name': 'Pacjent',
                'verbose_name_plural': 'Pacjenci',
            },
        ),
    ]
