# Generated by Django 4.1.4 on 2023-01-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lekarze', '0004_lek_pacjent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='user',
        ),
    ]
