# Generated by Django 4.1.4 on 2023-01-13 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lekarze', '0006_users_pacjent_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_badania', models.DecimalField(decimal_places=0, max_digits=5)),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Badanie',
                'verbose_name_plural': 'Badania',
            },
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.DecimalField(decimal_places=0, max_digits=11)),
                ('lek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lekarze.lek')),
            ],
            options={
                'verbose_name': 'Recepta',
                'verbose_name_plural': 'Recepty',
            },
        ),
        migrations.CreateModel(
            name='Skierowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.DecimalField(decimal_places=0, max_digits=11)),
                ('badanie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lekarze.lek')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Recepty',
            },
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 16, 44, 39, 736932)),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='pesel',
            field=models.IntegerField(max_length=11),
        ),
        migrations.DeleteModel(
            name='Pacjent',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
